/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OidcCallbackRouteImport } from './routes/oidc-callback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardUsageRouteImport } from './routes/dashboard/usage'
import { Route as DashboardSkillsRouteImport } from './routes/dashboard/skills'
import { Route as DashboardSessionsRouteImport } from './routes/dashboard/sessions'
import { Route as DashboardRulesRouteImport } from './routes/dashboard/rules'
import { Route as DashboardRequestsRouteImport } from './routes/dashboard/requests'
import { Route as DashboardQueueRouteImport } from './routes/dashboard/queue'
import { Route as DashboardPoliciesRouteImport } from './routes/dashboard/policies'
import { Route as DashboardOrgRouteImport } from './routes/dashboard/org'
import { Route as DashboardInferenceRouteImport } from './routes/dashboard/inference'
import { Route as DashboardComplianceRouteImport } from './routes/dashboard/compliance'
import { Route as DashboardAuditRouteImport } from './routes/dashboard/audit'
import { Route as DashboardApprovalsRouteImport } from './routes/dashboard/approvals'
import { Route as DashboardAgentsRouteImport } from './routes/dashboard/agents'
import { Route as DashboardSettingsSecretsRouteImport } from './routes/dashboard/settings/secrets'
import { Route as DashboardSettingsOpsRouteImport } from './routes/dashboard/settings/ops'
import { Route as DashboardSettingsInferenceRouteImport } from './routes/dashboard/settings/inference'
import { Route as DashboardSessionsSessionIdRouteImport } from './routes/dashboard/sessions/$sessionId'
import { Route as DashboardQueueItemIdRouteImport } from './routes/dashboard/queue/$itemId'

const OidcCallbackRoute = OidcCallbackRouteImport.update({
  id: '/oidc-callback',
  path: '/oidc-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsageRoute = DashboardUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSkillsRoute = DashboardSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSessionsRoute = DashboardSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRulesRoute = DashboardRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRequestsRoute = DashboardRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQueueRoute = DashboardQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPoliciesRoute = DashboardPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrgRoute = DashboardOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInferenceRoute = DashboardInferenceRouteImport.update({
  id: '/inference',
  path: '/inference',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardComplianceRoute = DashboardComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApprovalsRoute = DashboardApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsSecretsRoute =
  DashboardSettingsSecretsRouteImport.update({
    id: '/settings/secrets',
    path: '/settings/secrets',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsOpsRoute = DashboardSettingsOpsRouteImport.update({
  id: '/settings/ops',
  path: '/settings/ops',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsInferenceRoute =
  DashboardSettingsInferenceRouteImport.update({
    id: '/settings/inference',
    path: '/settings/inference',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSessionsSessionIdRoute =
  DashboardSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => DashboardSessionsRoute,
  } as any)
const DashboardQueueItemIdRoute = DashboardQueueItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => DashboardQueueRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/oidc-callback': typeof OidcCallbackRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/inference': typeof DashboardInferenceRoute
  '/dashboard/org': typeof DashboardOrgRoute
  '/dashboard/policies': typeof DashboardPoliciesRoute
  '/dashboard/queue': typeof DashboardQueueRouteWithChildren
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/rules': typeof DashboardRulesRoute
  '/dashboard/sessions': typeof DashboardSessionsRouteWithChildren
  '/dashboard/skills': typeof DashboardSkillsRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/queue/$itemId': typeof DashboardQueueItemIdRoute
  '/dashboard/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/dashboard/settings/inference': typeof DashboardSettingsInferenceRoute
  '/dashboard/settings/ops': typeof DashboardSettingsOpsRoute
  '/dashboard/settings/secrets': typeof DashboardSettingsSecretsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/oidc-callback': typeof OidcCallbackRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/inference': typeof DashboardInferenceRoute
  '/dashboard/org': typeof DashboardOrgRoute
  '/dashboard/policies': typeof DashboardPoliciesRoute
  '/dashboard/queue': typeof DashboardQueueRouteWithChildren
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/rules': typeof DashboardRulesRoute
  '/dashboard/sessions': typeof DashboardSessionsRouteWithChildren
  '/dashboard/skills': typeof DashboardSkillsRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/queue/$itemId': typeof DashboardQueueItemIdRoute
  '/dashboard/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/dashboard/settings/inference': typeof DashboardSettingsInferenceRoute
  '/dashboard/settings/ops': typeof DashboardSettingsOpsRoute
  '/dashboard/settings/secrets': typeof DashboardSettingsSecretsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/oidc-callback': typeof OidcCallbackRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/inference': typeof DashboardInferenceRoute
  '/dashboard/org': typeof DashboardOrgRoute
  '/dashboard/policies': typeof DashboardPoliciesRoute
  '/dashboard/queue': typeof DashboardQueueRouteWithChildren
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/rules': typeof DashboardRulesRoute
  '/dashboard/sessions': typeof DashboardSessionsRouteWithChildren
  '/dashboard/skills': typeof DashboardSkillsRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/queue/$itemId': typeof DashboardQueueItemIdRoute
  '/dashboard/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/dashboard/settings/inference': typeof DashboardSettingsInferenceRoute
  '/dashboard/settings/ops': typeof DashboardSettingsOpsRoute
  '/dashboard/settings/secrets': typeof DashboardSettingsSecretsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/dashboard'
    | '/login'
    | '/oidc-callback'
    | '/dashboard/agents'
    | '/dashboard/approvals'
    | '/dashboard/audit'
    | '/dashboard/compliance'
    | '/dashboard/inference'
    | '/dashboard/org'
    | '/dashboard/policies'
    | '/dashboard/queue'
    | '/dashboard/requests'
    | '/dashboard/rules'
    | '/dashboard/sessions'
    | '/dashboard/skills'
    | '/dashboard/usage'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/queue/$itemId'
    | '/dashboard/sessions/$sessionId'
    | '/dashboard/settings/inference'
    | '/dashboard/settings/ops'
    | '/dashboard/settings/secrets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/login'
    | '/oidc-callback'
    | '/dashboard/agents'
    | '/dashboard/approvals'
    | '/dashboard/audit'
    | '/dashboard/compliance'
    | '/dashboard/inference'
    | '/dashboard/org'
    | '/dashboard/policies'
    | '/dashboard/queue'
    | '/dashboard/requests'
    | '/dashboard/rules'
    | '/dashboard/sessions'
    | '/dashboard/skills'
    | '/dashboard/usage'
    | '/dashboard/users'
    | '/dashboard'
    | '/dashboard/queue/$itemId'
    | '/dashboard/sessions/$sessionId'
    | '/dashboard/settings/inference'
    | '/dashboard/settings/ops'
    | '/dashboard/settings/secrets'
  id:
    | '__root__'
    | '/'
    | '/change-password'
    | '/dashboard'
    | '/login'
    | '/oidc-callback'
    | '/dashboard/agents'
    | '/dashboard/approvals'
    | '/dashboard/audit'
    | '/dashboard/compliance'
    | '/dashboard/inference'
    | '/dashboard/org'
    | '/dashboard/policies'
    | '/dashboard/queue'
    | '/dashboard/requests'
    | '/dashboard/rules'
    | '/dashboard/sessions'
    | '/dashboard/skills'
    | '/dashboard/usage'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/queue/$itemId'
    | '/dashboard/sessions/$sessionId'
    | '/dashboard/settings/inference'
    | '/dashboard/settings/ops'
    | '/dashboard/settings/secrets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OidcCallbackRoute: typeof OidcCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oidc-callback': {
      id: '/oidc-callback'
      path: '/oidc-callback'
      fullPath: '/oidc-callback'
      preLoaderRoute: typeof OidcCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/usage': {
      id: '/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof DashboardUsageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/skills': {
      id: '/dashboard/skills'
      path: '/skills'
      fullPath: '/dashboard/skills'
      preLoaderRoute: typeof DashboardSkillsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sessions': {
      id: '/dashboard/sessions'
      path: '/sessions'
      fullPath: '/dashboard/sessions'
      preLoaderRoute: typeof DashboardSessionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rules': {
      id: '/dashboard/rules'
      path: '/rules'
      fullPath: '/dashboard/rules'
      preLoaderRoute: typeof DashboardRulesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/requests': {
      id: '/dashboard/requests'
      path: '/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof DashboardRequestsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/queue': {
      id: '/dashboard/queue'
      path: '/queue'
      fullPath: '/dashboard/queue'
      preLoaderRoute: typeof DashboardQueueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/policies': {
      id: '/dashboard/policies'
      path: '/policies'
      fullPath: '/dashboard/policies'
      preLoaderRoute: typeof DashboardPoliciesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/org': {
      id: '/dashboard/org'
      path: '/org'
      fullPath: '/dashboard/org'
      preLoaderRoute: typeof DashboardOrgRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inference': {
      id: '/dashboard/inference'
      path: '/inference'
      fullPath: '/dashboard/inference'
      preLoaderRoute: typeof DashboardInferenceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/compliance': {
      id: '/dashboard/compliance'
      path: '/compliance'
      fullPath: '/dashboard/compliance'
      preLoaderRoute: typeof DashboardComplianceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/approvals': {
      id: '/dashboard/approvals'
      path: '/approvals'
      fullPath: '/dashboard/approvals'
      preLoaderRoute: typeof DashboardApprovalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agents': {
      id: '/dashboard/agents'
      path: '/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/secrets': {
      id: '/dashboard/settings/secrets'
      path: '/settings/secrets'
      fullPath: '/dashboard/settings/secrets'
      preLoaderRoute: typeof DashboardSettingsSecretsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/ops': {
      id: '/dashboard/settings/ops'
      path: '/settings/ops'
      fullPath: '/dashboard/settings/ops'
      preLoaderRoute: typeof DashboardSettingsOpsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/inference': {
      id: '/dashboard/settings/inference'
      path: '/settings/inference'
      fullPath: '/dashboard/settings/inference'
      preLoaderRoute: typeof DashboardSettingsInferenceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sessions/$sessionId': {
      id: '/dashboard/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/dashboard/sessions/$sessionId'
      preLoaderRoute: typeof DashboardSessionsSessionIdRouteImport
      parentRoute: typeof DashboardSessionsRoute
    }
    '/dashboard/queue/$itemId': {
      id: '/dashboard/queue/$itemId'
      path: '/$itemId'
      fullPath: '/dashboard/queue/$itemId'
      preLoaderRoute: typeof DashboardQueueItemIdRouteImport
      parentRoute: typeof DashboardQueueRoute
    }
  }
}

interface DashboardQueueRouteChildren {
  DashboardQueueItemIdRoute: typeof DashboardQueueItemIdRoute
}

const DashboardQueueRouteChildren: DashboardQueueRouteChildren = {
  DashboardQueueItemIdRoute: DashboardQueueItemIdRoute,
}

const DashboardQueueRouteWithChildren = DashboardQueueRoute._addFileChildren(
  DashboardQueueRouteChildren,
)

interface DashboardSessionsRouteChildren {
  DashboardSessionsSessionIdRoute: typeof DashboardSessionsSessionIdRoute
}

const DashboardSessionsRouteChildren: DashboardSessionsRouteChildren = {
  DashboardSessionsSessionIdRoute: DashboardSessionsSessionIdRoute,
}

const DashboardSessionsRouteWithChildren =
  DashboardSessionsRoute._addFileChildren(DashboardSessionsRouteChildren)

interface DashboardRouteChildren {
  DashboardAgentsRoute: typeof DashboardAgentsRoute
  DashboardApprovalsRoute: typeof DashboardApprovalsRoute
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardComplianceRoute: typeof DashboardComplianceRoute
  DashboardInferenceRoute: typeof DashboardInferenceRoute
  DashboardOrgRoute: typeof DashboardOrgRoute
  DashboardPoliciesRoute: typeof DashboardPoliciesRoute
  DashboardQueueRoute: typeof DashboardQueueRouteWithChildren
  DashboardRequestsRoute: typeof DashboardRequestsRoute
  DashboardRulesRoute: typeof DashboardRulesRoute
  DashboardSessionsRoute: typeof DashboardSessionsRouteWithChildren
  DashboardSkillsRoute: typeof DashboardSkillsRoute
  DashboardUsageRoute: typeof DashboardUsageRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSettingsInferenceRoute: typeof DashboardSettingsInferenceRoute
  DashboardSettingsOpsRoute: typeof DashboardSettingsOpsRoute
  DashboardSettingsSecretsRoute: typeof DashboardSettingsSecretsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgentsRoute: DashboardAgentsRoute,
  DashboardApprovalsRoute: DashboardApprovalsRoute,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardComplianceRoute: DashboardComplianceRoute,
  DashboardInferenceRoute: DashboardInferenceRoute,
  DashboardOrgRoute: DashboardOrgRoute,
  DashboardPoliciesRoute: DashboardPoliciesRoute,
  DashboardQueueRoute: DashboardQueueRouteWithChildren,
  DashboardRequestsRoute: DashboardRequestsRoute,
  DashboardRulesRoute: DashboardRulesRoute,
  DashboardSessionsRoute: DashboardSessionsRouteWithChildren,
  DashboardSkillsRoute: DashboardSkillsRoute,
  DashboardUsageRoute: DashboardUsageRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSettingsInferenceRoute: DashboardSettingsInferenceRoute,
  DashboardSettingsOpsRoute: DashboardSettingsOpsRoute,
  DashboardSettingsSecretsRoute: DashboardSettingsSecretsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OidcCallbackRoute: OidcCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
