// Package runtime — AgentRuntime and backends for SOLO and TEAM modes.
// backend.go defines the RuntimeBackend interface.
package runtime

import (
	"github.com/centralchurch/central-cli/internal/api"
	"github.com/centralchurch/central-cli/internal/config"
	"github.com/centralchurch/central-cli/internal/inference"
)

// ── RuntimeBackend interface ────────────────────────────────────
// Each mode (SOLO, TEAM) implements this interface, providing
// context preparation and tool execution to the AgentRuntime.

type RuntimeBackend interface {
	// Mode returns the runtime mode identifier (solo or team).
	Mode() config.RuntimeMode

	// Plan requests an InferencePlan — the canonical entry point for a turn.
	// In SOLO mode this builds messages/tools locally via ContextLite.
	// In TEAM mode this calls POST /assistant/plan on the VPS.
	Plan(userText string, sessionID string, history []inference.Message) (*api.InferencePlan, error)

	// PrepareContext builds messages and tools for the next inference turn.
	// Deprecated: use Plan() instead. Kept for backward compatibility.
	PrepareContext(userText string, sessionID string, history []inference.Message) (*api.InferencePlan, error)

	// ExecuteTools runs tool calls generated by the model.
	// In SOLO mode this runs in-process via ExecutorBridge.
	// In TEAM mode policy_digest from the InferencePlan gates write tools.
	ExecuteTools(toolCalls []inference.ToolCall, policy *api.PolicyDigest) ([]ToolResult, error)

	// ReportComplete reports the end of a turn.
	// In TEAM mode this calls POST /connector/inference-complete on the VPS.
	ReportComplete(requestID string, usage inference.Usage) error

	// CompleteTurn reports the end of a turn.
	// Deprecated: use ReportComplete() instead. Kept for backward compatibility.
	CompleteTurn(requestID string, usage inference.Usage) error

	// Workspace returns the active workspace path.
	Workspace() string

	// Provider returns the LLM inference provider.
	Provider() *inference.Provider

	// Status returns live runtime metrics for the TUI sidebar.
	Status() *RuntimeStatus

	// SetCallbacks registers streaming callbacks with the backend.
	SetCallbacks(cbs *AgentCallbacks)
}

// AgentCallbacks are invoked by the AgentRuntime during inference.
type AgentCallbacks struct {
	OnToken      func(token string)
	OnToolStart  func(name string, args map[string]any)
	OnToolResult func(name string, output string, err string)
	OnDone       func(usage inference.Usage)
	OnError      func(err error)
}
