/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OidcCallbackRouteImport } from './routes/oidc-callback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AgentTreesRouteImport } from './routes/agent-trees'
import { Route as IndexRouteImport } from './routes/index'

const OidcCallbackRoute = OidcCallbackRouteImport.update({
  id: '/oidc-callback',
  path: '/oidc-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentTreesRoute = AgentTreesRouteImport.update({
  id: '/agent-trees',
  path: '/agent-trees',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-trees': typeof AgentTreesRoute
  '/login': typeof LoginRoute
  '/oidc-callback': typeof OidcCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-trees': typeof AgentTreesRoute
  '/login': typeof LoginRoute
  '/oidc-callback': typeof OidcCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-trees': typeof AgentTreesRoute
  '/login': typeof LoginRoute
  '/oidc-callback': typeof OidcCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agent-trees' | '/login' | '/oidc-callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agent-trees' | '/login' | '/oidc-callback'
  id: '__root__' | '/' | '/agent-trees' | '/login' | '/oidc-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentTreesRoute: typeof AgentTreesRoute
  LoginRoute: typeof LoginRoute
  OidcCallbackRoute: typeof OidcCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oidc-callback': {
      id: '/oidc-callback'
      path: '/oidc-callback'
      fullPath: '/oidc-callback'
      preLoaderRoute: typeof OidcCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-trees': {
      id: '/agent-trees'
      path: '/agent-trees'
      fullPath: '/agent-trees'
      preLoaderRoute: typeof AgentTreesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentTreesRoute: AgentTreesRoute,
  LoginRoute: LoginRoute,
  OidcCallbackRoute: OidcCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
